spring.application.name=FORCE-reservas-backend
# URL de conexión (por defecto corre en el puerto 5432 y 'tu_base_datos' es el nombre que le diste en pgAdmin)
spring.datasource.url=jdbc:postgresql://localhost:5432/tu_base_datos

# Tus credenciales de acceso a Postgres
spring.datasource.username=postgres
spring.datasource.password=tu_contraseña

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' creará las tablas automáticamente en tu base de datos basándose en tus entidades de Java
spring.jpa.hybrid.ddl-auto=update
spring.jpa.show-sql=true